Do homework 3
tayvazyan/ta-academy_3 pull request #3
Opened 2023-10-25 21:51 UTC by tayvazyan

2023-10-26 12:04 UTC, valeriyazin requested changes

2023-10-26 12:04 UTC, valeriyazin commented on manual/lesson_3/homework_3/UHC.postman_collection.json
> +							"  pm.expect(jsonData.customer.uvp.planId).to.be.a(\"integer\");",
please change 'integer' to 'number'

2023-10-26 12:04 UTC, valeriyazin commented on manual/lesson_3/homework_3/UHC.postman_collection.json
> +							"  pm.expect(jsonData.customer.uvp.planId.title).to.be.a(\"string\");",
this field doesn't exist in the  documentation

2023-10-26 12:44 UTC, tayvazyan commented on manual/lesson_3/homework_3/UHC.postman_collection.json
> +							"  pm.expect(jsonData.customer.uvp.planId).to.be.a(\"integer\");",
Thanks, done

2023-10-26 12:44 UTC, tayvazyan commented on manual/lesson_3/homework_3/UHC.postman_collection.json
> +							"  pm.expect(jsonData.customer.uvp.planId.title).to.be.a(\"string\");",
Thanks, fixed

2023-10-28 19:22 UTC, valeriyazin approved these changes

2023-10-28 19:23 UTC, merged